apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production
resources:
  - ../base
patchesStrategicMerge: []
images:
  - name: keyholesoftware/now-playing-api
    newName: keyholesoftware/now-playing-api # {"$imagepolicy": "production:now-playing-api:name"}
    newTag: 8f8e022e-1659639961 # {"$imagepolicy": "production:now-playing-api:tag"}
