apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production
resources:
#   - ../base
# patchesStrategicMerge: []
# images:
#   - name: keyholesoftware/now-playing-api
#     newName: keyholesoftware/now-playing-api # {"$imagepolicy": "production:now-playing-api:name"}
#     newTag: b0f7e2a0-1660244553 # {"$imagepolicy": "production:now-playing-api:tag"}
# configMapGenerator:
#   - name: now-playing-api-feature-flags
#     behavior: replace
#     envs:
#       - now-playing-api-features.env
