apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - now-playing-api.yaml
# configMapGenerator:
#   - name: now-playing-api-feature-flags
#     envs:
#       - now-playing-api-features.env
